# Generated by Django 3.1.3 on 2020-11-23 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='capital_social',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='logradouro',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='message',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='motivo_situacao',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='socioNome',
        ),
    ]
